### ISSUE TITLE
Export Consolidated RouteTableIds 

### ISSUE THREAD

**Issue by ambsw-technology** [cfn-modules/vpc#14]
I'm trying to attach a `AWS::EC2::VPNGatewayRoutePropagation` to a `VpcModule` so I need `RouteTableIds`.  As a dynamic list, this is extremely difficult to build using just exports so it would be ideal if the module provided a consolidated export value to split.

**Comment by ambsw-technology** [comment]
I suppose I really need the `PublicRouteTableIds` in `aws-cfn-modules` but it seems important to be able to access these lists by export since they're dynamic.

**Comment by michaelwittig** [comment]
see latest version 1.3.0. New outputs:

* RouteTableIdsPublic
* RouteTableIdsPrivate
