### ISSUE TITLE
Question: Referencing the default security group

### ISSUE THREAD

**Issue by nason** [cfn-modules/vpc#4]
Hi, thanks for these sweet modules! I'm using this VPC module and would like to reference the default security group for the VPC in CloudFormation.

Is there a good way to do that? I don't see it in the outputs and am not sure how without making some API calls first.

**Comment by michaelwittig** [comment]
Hi @nason I just checked that the `AWS::EC2::VPC` supports the attribute `DefaultSecurityGroup` so we could forward this value as an output of the module. May I ask what you try to do with the default security group? Usually I create my own Security Groups and leave the default sg alone?

**Comment by nason** [comment]
Thank you for the thoughtful response. You are very right-- I don't really need the default group.

I made one for my app and can reference that all I want.

**Comment by nason** [comment]
Hi @michaelwittig, I'm re-opening this after all...

I'd like to block all inbound and outbound traffic from a VPC's default security group, following the CIS AWS Foundations Standards:

> A VPC comes with a default security group whose initial settings deny all inbound traffic, allow all outbound traffic, and allow all traffic between instances assigned to the security group. If you don't specify a security group when you launch an instance, the instance is automatically assigned to this default security group. It is recommended that the default security group restrict all traffic.

I could do this if the default security group's id was exposed with a pair of `AWS::EC2::SecurityGroupIngress` + `AWS::EC2::SecurityGroupEgress`. Is this a valid use case for outputting this id, or is there another way to go about it?

**Comment by michaelwittig** [comment]
You somehow could, but only with a custom resource.

Security Groups can only Allow Traffic. You can not explicitly deny. The default security group comes with allow inbound/outbound rules and since they are not managed with CloudFormation you can also not delete them with CloudFormation.

The workaround is a custom resource that can do whatever you implement. Let me know if this is a solution for you and I'm happy to add the default sg id as an output.

**Comment by nason** [comment]
Well I'm glad I asked. Thank you so much for your insight, that is not at all how I thought this worked :)

We will look into a custom resource. Thanks again!
